### ISSUE TITLE
Nekos.Life commands do not work anymore

### ISSUE THREAD

**Issue by TsiJiang** [Nightorn/Aldebaran#85]
When using any command that pulls a picture from nekos.life, such as xrandom, it does not pull a picture and displays [object Object] instead.

1. Use xrandom, xkitty, xneko, etc command.
2. Bot posts an message containing "object Object" and the correctly programmed dialog associated with the command used.

**Expected behavior**
It seems that object Object is a placeholder for the picture and it is supposed to display a picture relating to the command used from a pool of pics on nekos.life. If I were to take a stab at solving it, try checking if the bot is still authorized to pull from that site.

**Aldebaran details:**
 - Version [e.g. 1.10.0]

**Comment by Ciborn** [comment]
Hello there!

Non-NSFW commands seem to be still working. It looks like only NSFW are affected, and checking [nekos.life's repo](https://github.com/Nekos-life/nekos-dot-life) indicates that all NSFW endpoints have been removed, breaking Aldebaran's functionality. As such, since I don't have any immediate solution, the affected NSFW commands will be removed from Aldebaran until I can find a replacement.

Thanks for the report, and thank you for using Aldebaran!
